# Generated by Django 4.2.17 on 2024-12-18 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'permissions': [('can_delete_comment', 'Can delete a comment')]},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_delete_post', 'Can delete a post')]},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'permissions': [('can_delete_topic', 'Can delete a topic')]},
        ),
    ]
