openapi: 3.0.0
info:
  title: Shneron
  version: 1.0.0
servers:
  - url: http://localhost:8000
paths:
  /:
    get:
      tags:
        - default
      summary: Registration Page
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Register
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                username:
                  type: string
                  example: omaryasser
                password:
                  type: string
                  example: df
                email:
                  type: string
                  example: s-omar@gmail.com
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: COzyWEEQPmoh9AxB979qQ0JwP13MgmN7
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login:
    get:
      tags:
        - default
      summary: login page
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /login/:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                username:
                  type: string
                  example: omaryasser
                password:
                  type: string
                  example: df
                next:
                  type: string
                  example: /favourites/
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: mv8TZdw0gVmkkCXrtcthM9Jl78r2c5Fz
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /search/search:
    get:
      tags:
        - default
      summary: search page
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /search/search/:
    post:
      tags:
        - default
      summary: Search
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                q:
                  type: string
                  example: her
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: hmvY5b0AtdgH2YMgTgDBNfBVSHljBHzM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shenron/movies/:
    get:
      tags:
        - default
      summary: All movies Page
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: hmvY5b0AtdgH2YMgTgDBNfBVSHljBHzM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /shenron/movies/238:
    get:
      tags:
        - default
      summary: Movie Page
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: hmvY5b0AtdgH2YMgTgDBNfBVSHljBHzM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/:
    get:
      tags:
        - default
      summary: Forum Page
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: hmvY5b0AtdgH2YMgTgDBNfBVSHljBHzM
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Post  a topic
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                name:
                  type: string
                  example: postman
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: HOWQlT5Sfppr6Np9ivLj6f6eDA5KlZQQ
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/topic/12:
    get:
      tags:
        - default
      summary: topic page
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/topic/12/:
    post:
      tags:
        - default
      summary: post a post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                title:
                  type: string
                  example: postman post
                content:
                  type: string
                  example: post through postman
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: mv8TZdw0gVmkkCXrtcthM9Jl78r2c5Fz
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/post/12:
    get:
      tags:
        - default
      summary: post page
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/post/11/:
    post:
      tags:
        - default
      summary: comment on a psot
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                comment:
                  type: string
                  example: postman comment
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: mv8TZdw0gVmkkCXrtcthM9Jl78r2c5Fz
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /forum/post/12/:
    post:
      tags:
        - default
      summary: delete a post
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              properties:
                delete_post:
                  type: string
      parameters:
        - name: X-CSRFToken
          in: header
          schema:
            type: string
          example: mv8TZdw0gVmkkCXrtcthM9Jl78r2c5Fz
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /favourites:
    get:
      tags:
        - default
      summary: favourites
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /favourites/add/238:
    get:
      tags:
        - default
      summary: add to favourites
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /favourites/remove/238:
    get:
      tags:
        - default
      summary: remove from favourites
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /logout:
    get:
      tags:
        - default
      summary: logout
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}