name: Build and deploy container app to Azure Web App - Shenron

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # Step 1: Checkout code
=======

>>>>>>> c291f3f94ec034a2e448b8c7b0e68e453c20343d
      - uses: actions/checkout@v4

      # Step 2: Set up Python environment and install dependencies
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r shenron/requirements.txt

      # Step 3: Run tests
      - name: Run tests
        run: |
          python shenron/manage.py test

      # Step 4: Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: shenron.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build and push the Docker image to ACR
      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./shenron                  # Directory containing your codebase
          file: ./shenron/Dockerfile          # Path to your Dockerfile
          push: true                          # Push the image to ACR
          tags: shenron.azurecr.io/django-web-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # Step 1: Deploy to Azure Web App using the built Docker image
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shenron'                        # Name of your Azure Web App
          slot-name: 'Production'                    # Deployment slot (if applicable)
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: 'shenron.azurecr.io/django-web-app:${{ github.sha }}'
