name: Build and deploy container app to Azure Web App - Shenron

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
        
          python -m pip install --upgrade pip
          pip install -r shenron/requirements.txt
      - name: Cleanup Test Database
        run: |
          mysql -h ${{ secrets.DATABASE_HOST }} -u ${{ secrets.DATABASE_USER }} -p${{ secrets.MYSQL_PASSWORD }} -e "DROP DATABASE IF EXISTS test_shenron_ci;"
      - name: Run tests
        env:
          DATABASE_NAME: 'shenron'
          DATABASE_USER: 'Alasil'
          DATABASE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          DATABASE_HOST: 'shenron.mysql.database.azure.com'
          DATABASE_PORT: '3306'
          SSL_CERT_PATH: './shenron/DigiCertGlobalRootCA.crt.pem'
        run: |
          # Ensure the SSL certificate is in the same directory as `manage.py`
          # ls -la shenron  # Optional: Debug to confirm the certificate is present
      
          # Navigate to the `shenron` directory containing `manage.py`
          cd shenron
          python manage.py collectstatic --noinput
          # Run Django tests
          python manage.py test --noinput --keepdb

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: shenron.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./shenron                 
          file: ./shenron/Dockerfile          
          push: true                        
          tags: shenron.azurecr.io/django-web-app:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'shenron'                      
          slot-name: 'Production'                   
          publish-profile: ${{ secrets.AzureAppService_PublishProfile }}
          images: 'shenron.azurecr.io/django-web-app:${{ github.sha }}'
